version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mern_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: mern_backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mern_db
      - PORT=5000
    depends_on:
      - mongo
    command: sh -c "npm install && npm start"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mern_frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped

volumes:
  mongo_data:
